config/routes.rb
Rails.application.routes.draw do
  mount FullcalendarEngine::Engine => "/calendar"
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :sermons, except: :show
    root to: 'home#index'
    resources :users
  end

  namespace :member do
    resources :sermons, except: :show
    root to: 'home#index'
  end
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
  validates :speaker, presence: true
  validates :subject, presence: true
  validates :day, presence: true

  mount_uploader :avatar, AvatarUploader

  scope :recent, -> { order(day: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :send_admin_mail

  ROLES = ["member", "admin"]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def approved
    approved? ? "Yes" : "No"
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  def send_admin_mail
    AdminMailer.new_registration_email(self).deliver
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

end

app/controllers/admin/sermons_controller.rb
class Admin::SermonsController < ApplicationController
  before_action :authenticate_user!, :set_sermon, only: [:edit, :update, :destroy]

  def index
    @sermons = Sermon.all
  end

  def new
    @sermon = Sermon.new
  end

  def edit
  end

  def create
    @sermon = Sermon.new(sermon_params)

    respond_to do |format|
      if @sermon.save
        format.html { redirect_to admin_sermons_path, notice: "The sermon has been uploaded." }
        format.json { render json: @sermon, status: 201, location: @sermon }
      else
        format.html { render :new }
        format.json { render json: @sermon.errors, status: 422 }
      end
    end
  end

  def update
    if @sermon.update(sermon_params)
      redirect_to admin_sermons_path, notice: "Sermon was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @sermon.destroy
    # redirect_to sermons_path, notice: "The sermon has been deleted."

    respond_to do |format|
      format.html { redirect_to admin_sermons_path }
      format.json { head :ok }
      format.js { render layout: false }
    end
  end

  private
    def set_sermon
      @sermon = Sermon.find(params[:id])
    end

    def sermon_params
      params.require(:sermon).permit(:speaker, :subject, :day, :avatar)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:approved] == "false"
      @users = User.find_all_by_approved(false)
    else
      @users = User.all
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        format.html { redirect_to admin_users_path, notice: "User created" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(user_params)

        UserMailer.user_approved_email(@user).deliver if @user.approved?

        format.html { redirect_to admin_users_path, notice: "User updated." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: "User deleted." }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role, :approved)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :set_layout


  def after_sign_in_path_for(user)
    if user.role == "admin"
      admin_root_path
    else
      member_root_path
    end
  end

  def after_sign_out_path_for(user)
    root_path
  end

  def set_layout
    if controller_path.starts_with?("member/")
      "member"
    elsif controller_path.starts_with?("admin/")
      "application"
    elsif devise_controller?
      "login"
    else
      "landing_page"
    end
  end
end

app/controllers/member/home_controller.rb
class Member::HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

end

app/controllers/member/sermons_controller.rb
class Member::SermonsController < ApplicationController
  before_action :authenticate_user!

  def index
    @sermons = Sermon.all
  end

  private
    def sermon_params
      params.require(:sermon).permit(:speaker, :subject, :day, :avatar)
    end
end

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController
  before_action :authenticate_user!

  def index
    @sermons = Sermon.all
  end

  private
    def sermon_params
      params.require(:sermon).permit(:speaker, :subject, :day, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.new_user_sign_up_email(@user).deliver

        format.html { redirect_to root_path, notice: "Your membership is pending approval" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role, :approved)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @user = User.first.decorate
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/index.html.erb
<h1>Admin dashboard</h1>

app/views/admin/sermons/_form.html.erb
<%= simple_form_for [:admin, @sermon], html: { multipart: true, class: 'form-vertical' } do |f| %>
    <%= f.input :speaker, placeholder: 'speaker name', label: false %>
    <%= f.input :subject, placeholder: 'topic', label: false %>
    <%= f.input_field :day, as: :date %>
    <br>
    <%= f.file_field :avatar %>
    <br>

    <div class="btn-toolbar">
    <%= f.button :submit, label: 'Add message', class: 'btn btn-primary' %>
    <%= link_to "Cancel", admin_sermons_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/sermons/_sermon.html.erb
<% @sermons.each do |sermon| %>
  <tr id="sermon_<%=sermon.id.to_s %>" >
    <td><%= sermon.speaker %></td>
    <td><%= sermon.subject %></td>
    <td><%= sermon.day.strftime("%m/%d/%Y") %></td>
    <td><%= audio_tag sermon.avatar.url, controls: true, autobuffer: true %></td>
    <td><%= link_to "Download", sermon.avatar.url %> | <%= link_to "Edit", edit_admin_sermon_path(sermon) %> | <%= link_to "Delete", [:admin, sermon], method: :delete, remote: true, data: { confirm: "Are you sure you want to delete this message?" } %></td>
  </tr>
<% end %>

app/views/admin/sermons/destroy.js.erb
$('#sermon_<%= (@sermon.id) %>').fadeOut();

app/views/admin/sermons/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Edit message</h1>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/sermons/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Messages</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10">
      <table id="example" class="table table-hover" cellspacing="0" width="90%">
        <thead>
          <tr>
            <th>Speaker</th>
            <th>Topic</th>
            <th>Date</th>
            <th>Listen</th>
            <th></th>
          </tr>
        </thead>
        <% if @sermons.present? %>
        <tbody id="sermon">
          <%= render 'sermon' %>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-2">
      <div class="pull-right">
        <%= link_to "Add a message", new_admin_sermon_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/sermons/index.js.erb
$('#sermon').html('<%= j render(partial: 'sermon') %>');

app/views/admin/sermons/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>New message</h1>
    </div>
    <div class="col-md-12">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user], html: { class: "form-vertical" } do |f| %>
  <%= f.input :email, label: false, placeholder: 'email' %>
  <%= f.input :role, as: :select, collection: User::ROLES, label: false, placeholder: 'role', include_blank: false %>
  <%= f.input :approved, as: :select, label: false, placeholder: 'approved status' %>

  <div class="btn-toolbar">
    <%= f.button :submit, label: 'Update member', class: 'btn btn-primary' %>
    <%= link_to "Cancel", admin_users_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/users/_new_user.html.erb
<%= simple_form_for [:admin, @user], html: { class: "form-vertical" } do |f| %>
  <%= f.input :email, label: false, placeholder: 'email' %>
  <%= f.input :password, label: false, placeholder: 'password' %>
  <%= f.input :password_confirmation, label: false, placeholder: 'password confirmation' %>
  <%= f.input :role, as: :select, collection: User::ROLES, label: false, placeholder: 'role', include_blank: false, default: 'member' %>
  <%= f.input :approved, as: :select, label: false, placeholder: 'approved status', default: false %>

  <div class="btn-toolbar">
    <%= f.button :submit, label: 'Create member', class: 'btn btn-primary' %>
    <%= link_to "Cancel", admin_users_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>Edit User</h1>
    </div>
    <div class="col-md-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>Members</h1>
    </div>
  </div>

  <%#= link_to "All Users", action: :index %>
  <%#= link_to "Users awaiting approval", action: :index, approved: "false" %>
  <div class="row">
    <div class="col-md-10">
      <% if @users.present? %>
        <table class="table table-striped table-hover table-responsive">
          <thead>
            <tr>
              <th>Email</th>
              <th>Joined</th>
              <th>Role</th>
              <th>Approved</th>
              <th></th>
            </tr>
          </thead>
          </tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= time_ago_in_words(user.created_at) %> ago</td>
              <td><%= user.role %></td>
              <td><%= user.approved %></td>
              <td><%= link_to "Edit", edit_admin_user_path(user) %> | <%= link_to "Delete", [:admin, user], data: { confirm: "Are you sure?" }, method: :delete %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <% else %>
        <br/>
        <p>No members have joined yet.</p>
        <br/>
      <% end %>
    </div>
    <div class="col-md-2">
      <div class="pull-left">
        <%= link_to "Add member", new_admin_user_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>New Member</h1>
    </div>
    <div class="col-md-12">
      <%= render 'new_user' %>
    </div>
  </div>
</div>

app/views/common/_notification.html.erb
<div class="col-md-offset-8">
  <div id="notification">
  <% flash.each do |name, msg| %>
    <% unless msg == true %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/layouts/_admin_navbar.html.erb
<% if current_user.role == "admin" %>
  <div class="custom-nav navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to '<i class="fa fa-home"></i>'.html_safe, main_app.root_path %><li>
      <li><%= link_to 'Admin Dashboard', main_app.admin_root_path %></li>
      <li><%= link_to 'Messages', main_app.admin_sermons_path %></li>
      <li><%= link_to 'Schedule', main_app.fullcalendar_engine_path %></li>
      <li><%= link_to 'Members', main_app.admin_users_path %></li>
      <li><a href="#">Announcements</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "#{current_user.email}", "#" %></li>
        <li><%= link_to "Log out", main_app.destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_member_navbar.html.erb
<% if current_user.role == "member" %>
  <div class="custom-nav navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to '<i class="fa fa-home"></i>'.html_safe, main_app.root_path %><li>
      <li><%= link_to 'Member Dashboard', main_app.member_root_path %></li>
      <li><%= link_to 'Messages', main_app.member_sermons_path %></li>
      <li><%= link_to 'Schedule', main_app.fullcalendar_engine_path %></li>
      <li><a href="#">Announcements</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "#{current_user.email}", "#" %></li>
        <li><%= link_to "Log out", main_app.destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PCIC</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <!-- <div class="container" style="padding-top:20px"> -->
    <%= yield %>
  <!-- </div> -->

</body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PCIC</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  <%= stylesheet_link_tag    'landing_page', media: 'all' %>
  <%= javascript_include_tag 'landing_page' %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <!-- Navigation -->
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <i class="fa fa-home"></i><span class="light">PCIC</span>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden"><a href="#page-top"></a></li>
                <li><a class="page-scroll" href="#about">About</a></li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a class="page-scroll" href="#messages">Messages</a></li>
                    <li><a class="page-scroll" href="#announcements">Announcements</a></li>
                  </ul>
                </li>

                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Contact <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a class="page-scroll" href="#contact">Contact Us</a></li>
                      <li><a class="page-scroll" href="#map">Directions</a></li>
                    </ul>
                </li>

                <% if user_signed_in? %>
                  <li>
                    <% if current_user.role == "member" %>
                      <%= link_to "Dashboard", member_root_path %>
                    <% elsif current_user.role == "admin" %>
                      <%= link_to "Dashboard", admin_root_path %>
                    <% end %>
                  </li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Log in", new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>

  <%= render '/common/notification' %>

  <%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PCIC</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  <%= stylesheet_link_tag 'login', media: 'all' %>
  <%#= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/common/notification' %>
  <%= yield %>

</body>
</html>

app/views/member/home/index.html.erb
<h1>HELLO MEMBER!</h1>

app/views/sermons/_sermon.html.erb
<% @sermons.each do |sermon| %>
  <tr id="sermon_<%=sermon.id.to_s %>" >
    <td><%= sermon.speaker %></td>
    <td><%= sermon.subject %></td>
    <td><%= sermon.day.strftime("%m/%d/%Y") %></td>
    <td><%= audio_tag sermon.avatar.url, controls: true, autobuffer: true %></td>
    <td><%= link_to "Download", sermon.avatar.url %></td>
    <td><%= button_to "Edit", edit_sermon_path(sermon), class: "btn btn-success", method: :get %></td>
    <td><%= link_to "Delete", sermon, method: :delete, remote: true, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this message?" } %></td>
  </tr>
<% end %>

app/views/sermons/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Messages</h2>
  </div>
  <div class="row">
    <div class="col-md-10">

      <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th>Speaker</th>
            <th>Topic</th>
            <th>Date</th>
            <th>Listen</th>
            <th>Download</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <% if @sermons.present? %>
        <tbody id="sermon">
          <%= render 'sermon' %>
        <% end %>
        </tbody>
      </table>

      <%= link_to "Add a message", new_sermon_path, class: "btn btn-default btn-sm" %>
      <br />
      <br />
      <%= link_to "Back", root_path, class: "btn btn-default btn-sm" %>
    </div>
  </div>

app/views/welcome/index.html.erb
<!-- Intro Header -->
<header class="intro">
  <div class="intro-body">
      <div class="container">
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  <h1 class="brand-heading">PCIC</h1>
                  <p class="intro-text">Peninsula Church in Christ</p>
                  <a href="#about" class="btn btn-circle page-scroll">
                      <i class="fa fa-angle-double-down animated"></i>
                  </a>
              </div>
          </div>
      </div>
  </div>
</header>


<!-- About Section -->
<section id="about" class="container content-section text-center">
  <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
          <h2>About PCIC</h2>
          <h4>Christ - the Eternal Purpose of God</h4>
          <p>For the administration of the fulness of times; to head up all things in the Christ, the things in the heavens and the things upon the earth; in him (Ephesians 1:10)</p>
          <h4>Cross – the Way to the Eternal Purpose of God</h4>
          <h4>Church - which is his body, the fulness of him who fills all in all: (Ephesians 1:23)</h4>
          <p>In the eternality past God purposed a purpose in His Beloved Son. God created all things, including men, for His Son. All the creation is to manifest the fullness and glory of Christ. Though man sinned and failed, God’s purpose does not fail.  In the fullness of time, God sent His only begotten Son to this world. Through His death on the cross, He opened a new and living way for men to reconcile to God.  By faith through grace we are called to be the Body of Christ to manifest the fullness of Christ.  By the work of Holy Spirit the Self life is put to death, the life of Christ is abound.</p>
      </div>
  </div>
</section>

<!-- Schedule Section -->
<section id="schedule" class="content-section text-center">
  <div class="schedule-section">
    <div class="container">
      <div class="col-lg-8 col-lg-offset-2" role="tabpanel">
        <h2>Schedule</h2>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="tabstyle active"><a href="#sunday" aria-controls="sunday" role="tab" data-toggle="tab">Sunday</a></li>
          <li role="presentation" class="tabstyle"><a href="#tuesday" aria-controls="tuesday" role="tab" data-toggle="tab">Tuesday</a></li>
          <li role="presentation" class="tabstyle"><a href="#friday" aria-controls="friday" role="tab" data-toggle="tab">Friday</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="sunday"><%= render 'sunday' %></div>
          <div role="tabpanel" class="tab-pane" id="tuesday"><%= render 'tuesday' %></div>
          <div role="tabpanel" class="tab-pane" id="friday"><%= render 'friday' %></div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Message Section -->
<section id="messages" class="content-section text-center">
  <div class="message-section">
      <div class="container">
          <div class="col-lg-8 col-lg-offset-2">
              <h2>Messages</h2>
              <p>Log in to download or listen to messages.</p>
               <% if user_signed_in? && current_user.role == "admin" %>
                    <%= link_to "Messages", admin_sermons_path, class: "btn btn-default btn-lg" %>
                <% elsif user_signed_in? && current_user.role == "member" %>
                    <%= link_to "Messages", member_sermons_path, class: "btn btn-default btn-lg" %>
                <% else %>
                    <%= link_to "Messages", new_user_session_path, class: "btn btn-default btn-lg" %>
                <% end %>
                <p></p>
              <p><%= link_to "Sign up", new_user_registration_path %> for an account if you don't have one.
              <br/>An account is created after you are approved by the administrator.</p>
          </div>
      </div>
  </div>
</section>

<!-- Contact Section -->
<section id="contact" class="container content-section text-center">
  <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
          <h2>Contact PCIC</h2>
          <p>Feel free to email us for any questions/comments.</p>
          <p><a href="mailto:peninsulachurchinchrist@gmail.com">peninsulachurchinchrist@gmail.com</a>
          </p>
          <!-- <ul class="list-inline banner-social-buttons">
              <li>
                  <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
              </li>
              <li>
                  <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
              </li>
              <li>
                  <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
              </li>
          </ul> -->
      </div>
  </div>
</section>

<!-- Map Section -->
<div>
  <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3170.0270061879196!2d-122.07866780000002!3d37.3891936!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb73218527229%3A0x213f2bca001e4bb2!2s596+Mercy+St%2C+Mountain+View%2C+CA+94041!5e0!3m2!1sen!2sus!4v1422629412651" frameborder="0" style="border:0" margin-top="100px"></iframe>
</div>

<!-- Footer -->
<footer>
  <div class="container text-center">
      <p>Copyright &copy; PCIC 2014</p>
  </div>
</footer>